### ISSUE TITLE
Updates & ideas

### ISSUE THREAD

**Issue by AlienMiner303** [kryptokrona/xmrig-android#3]
Wondering if we could update the mining pools in the android script when prompted or be able to manually add pools? Also, when I try to get into the config.json file in termux, it loads up blank and I am unable to change anuthing or especially amount of threads I want to use per phone and there is also no way to create worker names for each phone to show up on pool. If there is a way to implement these changes I believe it would help phone mining tremendously for xkr
Thanks

**Comment by f-r00t** [comment]
Hey! I have updated it just now. The android miner actually has it's own repo here btw: https://github.com/kryptokrona/xmrig-android

Enjoy!

**Comment by AlienMiner303** [comment]
Awesome! Thank you very much, can't wait to get in and check it out after work today
